#!/usr/bin/env python3
"""
png_to_rgb565.py  —  BeeBotix image converter
Converts a PNG to a C header containing a uint16_t RGB565 array.

Usage:
    python3 png_to_rgb565.py <input.png> <output.h> <array_name>

Output header defines:
    extern const uint16_t <array_name>[W * H];
    extern const uint16_t <array_name>_width;
    extern const uint16_t <array_name>_height;

Pixels are stored in row-major order, big-endian RGB565
(byte-swapped ready for GC9A01A wire format — matches beepi_hal_write_pixels).
"""

import sys
import struct

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} input.png output.h array_name")
        sys.exit(1)

    src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]

    # ---- Decode PNG without external libs (pure stdlib) --------------------
    # We use the 'struct' + 'zlib' modules only — both stdlib.
    import zlib, io

    with open(src, 'rb') as f:
        raw = f.read()

    sig = raw[:8]
    if sig != b'\x89PNG\r\n\x1a\n':
        print("ERROR: not a valid PNG file")
        sys.exit(1)

    chunks = {}
    pos = 8
    idat_data = b''
    while pos < len(raw):
        length = struct.unpack('>I', raw[pos:pos+4])[0]
        ctype  = raw[pos+4:pos+8].decode('ascii')
        data   = raw[pos+8:pos+8+length]
        pos   += 12 + length
        if ctype == 'IHDR':
            chunks['IHDR'] = data
        elif ctype == 'IDAT':
            idat_data += data
        elif ctype == 'IEND':
            break

    ihdr   = chunks['IHDR']
    width  = struct.unpack('>I', ihdr[0:4])[0]
    height = struct.unpack('>I', ihdr[4:8])[0]
    bit_depth    = ihdr[8]
    color_type   = ihdr[9]
    interlace    = ihdr[12]

    if interlace != 0:
        print("ERROR: interlaced PNG not supported — re-save as non-interlaced")
        sys.exit(1)
    if bit_depth != 8:
        print(f"ERROR: only 8-bit PNG supported (got {bit_depth}-bit)")
        sys.exit(1)
    # color_type: 2=RGB, 6=RGBA
    if color_type not in (2, 6):
        print(f"ERROR: only RGB (type 2) and RGBA (type 6) PNG supported (got type {color_type})")
        sys.exit(1)

    channels = 3 if color_type == 2 else 4
    raw_pixels = zlib.decompress(idat_data)

    # PNG filter reconstruction
    stride = width * channels
    pixels = []   # list of (r,g,b) tuples

    def paeth(a, b, c):
        p = a + b - c
        pa, pb, pc = abs(p-a), abs(p-b), abs(p-c)
        if pa <= pb and pa <= pc: return a
        if pb <= pc: return b
        return c

    prev_row = bytes(stride)
    idx = 0
    for y in range(height):
        ftype = raw_pixels[idx]; idx += 1
        row   = bytearray(raw_pixels[idx:idx+stride]); idx += stride
        recon = bytearray(stride)
        for x in range(stride):
            a = recon[x - channels] if x >= channels else 0
            b = prev_row[x]
            c = prev_row[x - channels] if x >= channels else 0
            raw_b = row[x]
            if   ftype == 0: recon[x] = raw_b
            elif ftype == 1: recon[x] = (raw_b + a) & 0xFF
            elif ftype == 2: recon[x] = (raw_b + b) & 0xFF
            elif ftype == 3: recon[x] = (raw_b + ((a + b) >> 1)) & 0xFF
            elif ftype == 4: recon[x] = (raw_b + paeth(a, b, c)) & 0xFF
        prev_row = recon
        for x in range(width):
            base = x * channels
            r, g, b2 = recon[base], recon[base+1], recon[base+2]
            pixels.append((r, g, b2))

    # ---- Convert to RGB565 big-endian (GC9A01A wire format) ----------------
    rgb565 = []
    for r, g, b in pixels:
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        # byte-swap to big-endian (what the display expects)
        swapped = ((v & 0xFF) << 8) | ((v >> 8) & 0xFF)
        rgb565.append(swapped)

    # ---- Write header -------------------------------------------------------
    with open(dst, 'w') as f:
        f.write(f'/* Auto-generated by png_to_rgb565.py — do not edit */\n')
        f.write(f'/* Source: {src}  ({width}x{height}) */\n\n')
        f.write(f'#pragma once\n')
        f.write(f'#include <stdint.h>\n\n')
        f.write(f'#define {name.upper()}_WIDTH  {width}u\n')
        f.write(f'#define {name.upper()}_HEIGHT {height}u\n\n')
        f.write(f'static const uint16_t {name}[{width * height}] = {{\n')

        per_line = 12
        for i, v in enumerate(rgb565):
            if i % per_line == 0:
                f.write('    ')
            f.write(f'0x{v:04X}')
            if i < len(rgb565) - 1:
                f.write(',')
            if i % per_line == per_line - 1 or i == len(rgb565) - 1:
                f.write('\n')
            else:
                f.write(' ')

        f.write('};\n')

    print(f"Converted {src} ({width}x{height}, {channels}ch) → {dst}  ({len(rgb565)} pixels)")

if __name__ == '__main__':
    main()